version: '3.8'

services:
  kit-service:
    image: php:8.2-cli
    ports:
      - "8000:8000"
    volumes:
      - ./kit-service:/app
    working_dir: /app
    command: php artisan serve --host=0.0.0.0 --port=8000

  order-service:
    image: php:8.2-cli
    ports:
      - "8001:8001"
    volumes:
      - ./order-service:/app
    working_dir: /app
    command: php artisan serve --host=0.0.0.0 --port=8001

  api-gateway:
    image: php:8.2-cli
    ports:
      - "8002:8002"
    volumes:
      - ./api-gateway:/app
    working_dir: /app
    command: php artisan serve --host=0.0.0.0 --port=8002

  finance-service:
    image: php:8.2-cli
    ports:
      - "8003:8003"
    volumes:
      - ./finance-service:/app
    working_dir: /app
    command: php -S 0.0.0.0:8003